### PR TITLE
Set up pre-commit hooks to enhance code formatting and linting

### PR DESCRIPTION
**Pull request by ben9809**
This pull request introduces pre-commit hooks to our project to automate and enhance code quality. Integrating these hooks will ensure that every commit complies with our coding standards.

Changes include:
- Added a `.pre-commit-config.yaml` file configuring Black and Flake8.
- Configured Black for consistent code formatting.
- Configured Flake8 for linting, helping identify and prevent potential code quality issues.

Developers must set up pre-commit on their local environments to benefit from these hooks.

### CODE REVIEW

**Comment by jasonlyik** [comment]
@ben9809 Looks pretty good.
I tried setting up a test file and I noticed the following:
- The file is skipped by pre-commit unless it is tracked by `git add`
- After automatic reformatting, I will need to `git add` again in order to track the format changes.

These are both expected behavior, right? I think we can add a bit more detail to the contributing text if so.

**Comment by ben9809** [comment]
Yes, the behavior you're observing is expected when working with pre-commit hooks in git.
It's a good idea to clarify these points in the contributing guidelines, I'll take care of it!

**Comment by ben9809** [comment]
I'd like to propose the following enhancement for our code quality process:

we could enforce our code quality standards server-side, by integrating pre-commit checks into our GitHub Actions workflow, such that if a developer forgets to run pre-commit locally, our codebase's integrity is safeguarded, as the checks will automatically run on the server when a pull request is opened on the dev branch. (This is still not integrated into this pull request)

Let me know your thoughts @jasonlyik!

**Comment by jasonlyik** [comment]
Sounds great, I think doing the server-side checks and making the format changes at PR time sounds pretty good, so that it's easier to develop locally.

**Comment by ben9809** [comment]
@jasonlyik Before we merge this pull request, I'd like to discuss some issues with certain files during our next development meeting. This way, we can decide together how to manage them!

**Comment by jasonlyik** [comment]
Sounds good, let's take a look next meeting

**Pull request merged**
